### ISSUE TITLE
'open in colab' link is broken

### ISSUE THREAD

**Issue by mialondon** [kingsdigitallab/lwm-davizct#1]
...because the files were reorganised

The link is https://colab.research.google.com/github/kingsdigitallab/lwm-davizct/blob/main/notebooks/LwM_DAVIZCT_Explore.ipynb

But it should be 
https://colab.research.google.com/github/kingsdigitallab/lwm-davizct/blob/main/notebooks/Explore.ipynb

**Comment by jmiguelv** [comment]
Will fix.
