### ISSUE TITLE
Is the 'Disambiguate subjects? Only needed if there are duplicate subjects in the data' checkbox still relevant?

### ISSUE THREAD

**Issue by mialondon** [kingsdigitallab/lwm-davizct#3]
If so, where does it take effect?

**Comment by mialondon** [comment]
I assume in the 'disambiguate_subjects = disambiguate_subjects_widget.value' and code under the 'Disambiguate subjects' heading, but what material effect does it have on which datasets?

**Comment by mialondon** [comment]
Should there be more explicit instructions re the option above and the note 'Warning: Depending on the amount of data, this step may be too time consuming to run on Colab' - and perhaps put the sections closer together?

It might be obvious to people who know the history of the code (and the unusual many-people journey of data from LwM to Zooniverse).

**Comment by mialondon** [comment]
Running it today with
- the 'disambiguate' flat on and 
- the exported files as in https://drive.google.com/drive/folders/1d4XK4iNlw4XcfhRZDxnuKccABfh2qjMI?usp=sharing 
 
I got the error message 'Looks like there are files with the same name that are different from one another. This should not be the case  with downloaded data from Zooniverse'

**Comment by jmiguelv** [comment]
The option takes effect in the Project section, and is relevant/needed if there might be duplicates. The operation affects the subjects data set.

Yes, agree, the warning about collab can be moved closer to the checkbox.

I am not able to access the exported files, but I have seen this before when I had multiple versions of the same subject that had been download with different names. Removing the offending files and re-downloading fixes the issue.
