### ISSUE TITLE
Observable 'aboutTheData' text is about the Accidents workflow, we need a version for Mechanisation

### ISSUE THREAD

**Issue by mialondon** [kingsdigitallab/lwm-davizct#6]
e.g. not only public domain titles, not only titles digitised for the project, different classification options

**Comment by mialondon** [comment]
@jmiguelv I duplicated aboutTheData() to make
aboutTheDataAccidents
aboutTheDataMechanisation

I've updated https://observablehq.com/d/fa057dffd570f948

**Comment by jmiguelv** [comment]
Thank you @mialondon, the accidents and mechanisation original notebooks have been updated as well.
